#!/usr/bin/env bash
set -euo pipefail

# Checked against official docs on 2026-03-07.
JDK_MAJOR="${JDK_MAJOR:-25}"
NODE_VERSION="${NODE_VERSION:-24.14.0}"
MAVEN_VERSION="${MAVEN_VERSION:-3.9.13}"
GRADLE_VERSION="${GRADLE_VERSION:-9.3.1}"
SBT_VERSION="${SBT_VERSION:-1.12.5}"
SCALA_LTS_VERSION="${SCALA_LTS_VERSION:-3.3.7}"
KOTLIN_VERSION="${KOTLIN_VERSION:-2.3.10}"
TYPESCRIPT_VERSION="${TYPESCRIPT_VERSION:-5.9.2}"
DUNE_LANG_VERSION="${DUNE_LANG_VERSION:-3.21}"

